app:
  dataSource:
    postgres:
      port: 5432
      username: postgres
      password: sa
      host: localhost
      databaseName: pokemon
      jdbc-url: jdbc:postgresql://${app.dataSource.postgres.host}:${app.dataSource.postgres.port}/${app.dataSource.postgres.databaseName}